- hosts: all
  become: yes
  tasks:
    - name: Set the Server Hostname
      hostname:
        name: cj-web01

    - name: Install patches
      dnf:
        name: "*"
        state: latest

    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configure webpage
      copy:
        content: "Welcome to \"{{ ansible_hostname }}\""
        dest: /var/www/html/index.html
